export const CART_ADD_PRESENTS = 'CART_ADD_PRESENTS' // request
export const CART_PRESENTS_CREATE = 'CART_PRESENTS_UPDATE' // request
export const CART_PRESENTS_DELETE = 'CART_PRESENTS_DELETE' // request
export const CART_PRESENTS_CHANGE = 'CART_PRESENTS_CHANGE' // may be create action or delete actions
export const CART_MERGE_PRESENTS = 'CART_MERGE_PRESENTS'
export const CART_REMOVE_PRESENTS = 'CART_REMOVE_PRESENTS'
export const LOGIN_ACTION = 'LOGIN_ACTION' // request
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const PRESENT_APPEND = 'PRESENT_APPEND'
export const PRESENT_FILITER = 'PRESENT_FILITER' // request
export const PRESENT_REINIT = 'PRESENT_REINIT'
export const PRESENT_REFRESH = 'PRESENT_REFRESH' // request
export const PRESENT_MERGE = 'PRESENT_MERGE'
export const PRESENT_GET_BY_ID = 'PRESENT_GET_BY_ID' // request
